apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: db

spec:
  serviceName: postgres
  replicas: {{ .Values.postgres.replicaCount }}

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db

    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}

          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu | quote }}
              memory: {{ .Values.postgres.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu | quote }}
              memory: {{ .Values.postgres.resources.limits.memory | quote }}

          livenessProbe:
            tcpSocket:
              port: {{ .Values.postgres.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: {{ .Values.postgres.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: {{ .Values.postgres.storage }}