apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: {{ .Values.namespace }}
  labels:
    app: vote

spec:
  replicas: {{ .Values.vote.replicaCount }}

  selector:
    matchLabels:
      app: vote

  template:
    metadata:
      labels:
        app: vote

    spec:
      containers:
        - name: vote

          image: "{{ .Values.vote.image.repository }}:{{ .Values.vote.image.tag }}"
          imagePullPolicy: {{ .Values.vote.image.pullPolicy }}

          ports:
            - containerPort: 80

          env:
            - name: REDIS_HOST
              value: redis

          resources:
            requests:
              cpu: {{ .Values.vote.resources.requests.cpu | quote }}
              memory: {{ .Values.vote.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.vote.resources.limits.cpu | quote }}
              memory: {{ .Values.vote.resources.limits.memory | quote }}

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5